apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-svc
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: nginx-port
      protocol: TCP
      port: 30000
      targetPort: 80
      nodePort: 32000
