kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-persistentvolume
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ec2-user/share"
