## ClusterIp yaml file

apiVersion: v1
kind: Service
metadata:
  name: service-clusterip-1
  namespace: dev
spec:
  selector:
   app: web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
