apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-demo-eks-cluster
  region: ap-south-1
  version: "1.21"
vpc:
  subnets:
    public:
      ap-south-1a: { id:subnet-e9190a81 }
      ap-south-1b: { id:subnet-d866eda3 }
managedNodeGroups:
  - name: my-demo-eks-workernodes
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    instanceType: t2.small
    labels: {role: dev.eks-workernode.role }
    ssh:
      publicKeyName: admin
    tags:
      nodegroup-role: dev.eks-workernode.role
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
