---
apiVersion: v1
kind: Namespace
metadata:
  name: testns
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: testns
spec:
  containers:
    - name: nginx-con1
      image: nginx:1.19
      ports:
        - containerPort: 80
  initContainers:
    - name: ping-test
      image: busybox:1.28
      args:
        - /bin/sh
        - -c
        - ping -c 150 amazon.com
