## How to create Namespace and Pod together using single Manifest file.yaml ?
## Answer is below,

---
apiVersion: v1
kind: Namespace
metadata:
name: development
---
apiVersion: v1
kind: Pod
metadata:
name: devpod
namespace: development
spec:
containers:
- name: nginx-container
image: nginx:1.18
ports:
- containerPort: 80
- name: http-container
image: httpd:2.4.52
ports:
- containerPort: 9090

## Note: After Namespace instruction, we need to give '---' (3 dash). Then you can start of yours.
