## Node Port yaml file

apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-1
  namespace: dev
spec:
  selector:
   app: web
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
