---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: dev-readonly-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-readonly-role-binding
  namespace: dev
subjects:
- kind: User
  name: eks-test-2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-readonly-role
  apiGroup: rbac.authorization.k8s.io
